### ISSUE TITLE
Basic Features List Missing

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/adopt-a-family#1]
## There are 3 primary user roles for the app

1. Community organizer (referred to as organizer from now on) eg Key Club, Rotoract, Church, etc.
2. Family in need (referred to as families)
3. Donors e.g. people/orgs from the community that want to help families in need

## General Goals
- Landing page explains what this app does and whom it can help
- Dashboard for folks to check status of event, see deadlines, etc
- Easily pair families with donators who have the budget to support their wishlist
- Allows organizer to easily communicate what's going on to families and donators
- Donators and families are alerted when there is a match and given an idea of what the timeline will be
- UX needs to be a high priority as folks may not be the most tech savvy

### Organizer
- Organizer can create a profile which has their contact info
- Organizer (such as a church, key club, rotoract, etc) can create the adopt-a-family event, which allows families and donators to sign up to participate in the event.
  - The event needs to have deadlines (start, end, check ins etc.)

### Families
- A family in need can go to the landing site and easily a profile which contains
  -  A picture(optional?)
  -  Who's in their family (family size)
  -  Contact info (private)
  -  Can create wishlist of things they need for their family

### Donors
- Sign up for a profile with info
  - Size of org
  - Budget
  - Person to contact (private)
- Receive wishlist of family
- Receive check-in dates/deadlines for when they need to get wishlist items

**Comment by phuchle** [comment]
### OP has been updated with my initial list of basic features.

**Comment by jwu910** [comment]
@phuchle is it safe to use this list and start generating some placeholder elements on each component? -- and/or start creating some reusable components for elements that would be in these? e.g. Input, InputPassword, Submit button, etc.
