### ISSUE TITLE
Unexpected token : in models branch

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/adopt-a-family#100]
Models branch merged with broken code:

https://travis-ci.org/5-gwoap/adopt-a-family/jobs/331676175

api.js line 40. I believe after efrain mentioned it, we need to remove "field" or "field"'s value should be within an object to be valid.

**Comment by rainrivas** [comment]
@jwu910 yep, I have that fixed in my local already. I'll push the fix up when I complete #97

**Comment by jwu910** [comment]
Sweet, got an issue for you :p
