### ISSUE TITLE
Mongo default array.push operator deprecated.

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/adopt-a-family#111]
Mongoose currently defaults to mongo's $pushAll array operator--deprecated since 2.4(?) The update is on the next release, but we'll need to address this issue until we decide to move our DB to that version.

We can set the property of 'usePushEach' on our schemas as a work around.
https://github.com/Automattic/mongoose/issues/4455 Read more here.

**Comment by rainrivas** [comment]
Closing as part of sprint 3
