### ISSUE TITLE
Add prettierrc

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/adopt-a-family#129]
We need a prettier config so contributors can utilize prettier to auto format their files.

**Comment by rainrivas** [comment]
@jwu910 
My Suggestions for code:

    Indents: 2 spaces (set your editor for tab to soft indent 2 spaces so you dont have to spam spaces)
    Variables: declare one per statement. lowerCamelCase for vars, funcs, descriptions. UpperCamelCase for classes. UPPERCASE_SNAKE for constants.
    Semicolons: yes

General:

    ES6 when possible.
    Use single quotes unless writing JSON or HTML.
    Create descriptive names for variables, conditionals, functions et al when sane. It's ok if you use a letter for the iterator in a for loop.


From #5

**Comment by rainrivas** [comment]
Also the notes in Discord:
```json
"prettier_options": {
        "printWidth": 80,
        "singleQuote": true,
        "trailingComma": "es5",
        "bracketSpacing": false,
        "jsxBracketSameLine": false,
        "parser": "babylon",
        "semi": true,
```
