### ISSUE TITLE
Introduce Typescript

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/adopt-a-family#141]
:man_shrugging:

**Comment by phuchle** [comment]
backend too 🤷‍♀

**Comment by rainrivas** [comment]
so we rewiting the whole thing lol

**Comment by jwu910** [comment]
https://tenor.com/wthO.gif 

Why not?

**Comment by phuchle** [comment]
https://medium.com/@clayallsopp/incrementally-migrating-javascript-to-typescript-565020e49c88#.l97u6kbhp

**Comment by jwu910** [comment]
Closed by #146 ;)
