### ISSUE TITLE
Basic Layout Needed

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/adopt-a-family#2]

**Comment by jwu910** [comment]
Will need to coordinate with designer to figure out some artwork needed for the site. Icons, jumbotrons, stock images, galleries.

**Comment by phuchle** [comment]
Getting the ball rolling here:

**Design ideas**
https://dribbble.com/shots/1390801-Survey-Analytics-UI-UX
https://dribbble.com/shots/2478322-Paperpillar-Studio-Landing-Page

**Landing**
Explanation of what adopt a family is 
I like the big cover image with room for a big slogan like in paperpillar above
You should be able to scroll through the landing page and get enough info about being a donor, family in need, or organizer
Sign up button in the nav and at the bottom (wherever you think makes sense)

**Sign-up page**
Email, password, sign up button

**Dashboard**
Alerts (eg Donors can't make deadlines, wishlist changes, etc)
Emails
Mini-calendar
Upcoming deadlines

**Profile**
_(family profiles viewable only to those participating in AAF event to protect IDs of families)_
Picture (optional) 
Name

**Comment by jwu910** [comment]
@phuchle <s>Under dashboard, Alerts (Donors can't.... ?</s> thanks!
Also, should our Landing page include information about 5-GWOAP or should have any information at ?

**Comment by phuchle** [comment]
@jwu910 updated the sentence fragment.

I think usually creator info is at the footer or about-us page but probably not any major area of focus on the landing page.

PS: You have editing powers over the comment so feel free to get in there.

**Comment by jwu910** [comment]
I wasn't sure what you were writing in that sentence fragment lol @phuchle 

Cool cool cool. Sounds good

**Comment by rainrivas** [comment]
I was thinking something clean and simple like this:
* https://www.awwwards.com/sites/hisense-uk
* https://www.awwwards.com/sites/design-by-roka
* https://www.awwwards.com/sites/studio-t

**Comment by jwu910** [comment]
I think that studio-t design is a little much hahahah. I was caught of guard when I started scrolling. 

First one hisense-uk was a little slow on the scroll for me. seems like the layout controls your scroll as you go down and until you get to the image with the 3 card links, you don't actually have a scroll bar

I like the cards on the second one, blocked off and good space for a gallery or profiles.

**Comment by rainrivas** [comment]
@jwu910 I like pieces of each UI but couldn't find a UX I liked

**Comment by jwu910** [comment]
@rainrivas thats cool, i think we make note of features we like, and we can consider implementing a frankenstein of features

**Comment by jwu910** [comment]
Basic layout with placeholder navigation in place. Merged in to development and closing issue.
