### ISSUE TITLE
Design Global Header/Footer

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/adopt-a-family#22]

**Comment by jwu910** [comment]
https://liferay.invisionapp.com/share/95DUMA0ZF

Please take a look and see if there are any changes we would like to see. Feedback is encouraged.

**Comment by RebWu** [comment]
https://liferay.invisionapp.com/share/95DUMA0ZF

**Comment by rainrivas** [comment]
I like it. It's simple and clean. We can probably work to start implementing this in our phase 2 of development for front end.

**Comment by jwu910** [comment]
We can discuss the plans tmrw. But def could start implemetning the base theme and structuring a lot of the framework to take in the styling classes.
