### ISSUE TITLE
Technologies Needed

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/adopt-a-family#4]
What tools do we plan on using; I believe @phuchle mentioned MERN

**Comment by rainrivas** [comment]
@phuchle @AlChiu @jwu910 @psyduc Do we need an editor config file or sorts for coding formats and style adherence or is that overkill?

**Comment by jwu910** [comment]
YES we can set up a linter file too. i have not done that yet.

**Comment by AlChiu** [comment]
I would say we should have at least a style format. Something like indenting with two spaces.

**Comment by rainrivas** [comment]
> I would say we should have at least a style format. Something like indenting with two spaces.

Tabs for life man. Can't be bothered to press space that many times

**Comment by AlChiu** [comment]
Well, I've set my sublime to just indent with two spaces with a tab key.

**Comment by rainrivas** [comment]
@AlChiu yeah @jwu910 was saying the same thing. we can do all that as part of the editor config file. We just need to make sure we follow the same templates. I can set up something like CI-type of style checks (which the linter should handle)

**Comment by jwu910** [comment]
I was typing space space space space in my terminal. no bueno. default nano/bash was giving me 8 spaces per tab. haven't looked in to it yet...

**Comment by phuchle** [comment]
I'm comfortable with MERN, and I have a bias toward React, but we can always start with the MEN and EJS as a template language to get a prototype rolling.  The EJS files can be ported to our desired front end when the functionality is built up.

**Comment by rainrivas** [comment]
@phuchle sounds good. I know EJS so no worries for me

**Comment by jwu910** [comment]
EJS looks just like freemarker/liquid. 

Edit: less like liquid, more like freemarker (java html templating)

**Comment by rainrivas** [comment]
@jwu910 think of JSP that you saw in java. EJS uses similar syntax where `%` is used to delimit the javascript portions of the hmtl.

```
app.get('/', function(req, res){ 
  res.render('index',{user:"John Smith"}) 
}); 
```
```
<html>
  <head><title><%= title %></title></head>
  <body>
    welcome <%= user%>;
  </body>
</html>
```

**Comment by jwu910** [comment]
Yep the HTML with the <%= variable %> looks the same.

Not familiar with app.get routing request and result stuff yet.

**Comment by jwu910** [comment]
<s>Next question React vs Preact.</s>

Looks like React is back on the table.

**Comment by rainrivas** [comment]
We going MERN so we closing this out
