### ISSUE TITLE
Redesign Header/Footer Components Based on redesign

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/adopt-a-family#44]
Make our header and footer look like #22

**Comment by phuchle** [comment]
https://www.adoptalovestory.com/

We like this header!

**Comment by rainrivas** [comment]
>https://www.adoptalovestory.com/
>
>We like this header!

We like this header's _experience_, the fact that is transitions and scrolls with content right?

**Comment by phuchle** [comment]
Correct.  The transition as you scroll is the desired effect.  The scroll-jacking is not lol

**Comment by jwu910** [comment]
https://github.com/5-gwoap/adopt-a-family/issues/22

Sorry repost
