### ISSUE TITLE
Redesign Footer

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/adopt-a-family#49]

**Comment by jwu910** [comment]
![image](https://user-images.githubusercontent.com/12107969/31534728-0197cfb0-afad-11e7-8940-3473ca565db5.png)

Pending Header styling

**Comment by jwu910** [comment]
@RebWu Gucci?

**Comment by jwu910** [comment]
Footer styling broken after Sass implementation. 

Require update to className's for Footer component to match with css's kebab-case naming conventions.

**Comment by rainrivas** [comment]
Is this in PR #70 @jwu910 ?

**Comment by jwu910** [comment]
Fixed
