### ISSUE TITLE
Refactor to remove constructor in React components

### ISSUE THREAD

**Issue by phuchle** [5-gwoap/adopt-a-family#65]
In most cases, we will not need the constructor.  Normal use cases for the constructor are:

- Binding methods
- Setting initial state

but I've recently learned that these can be done outside of the constructor (IE putting them directly onto the class).  Accessing `props` and `state` is still done via `this.props` and `this.state` in a class (and `props` in a stateless functional component), and accessing methods is still done via `this.bar()`.

**Example of old formatting**

```
class Foo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      a: 1, b: 2, c: 3
    }
    
    this.bar = this.bar.bind(this);
  }
  bar()  { ... }
}
```

**Example of new formatting**

```
class Foo extends Component { 
  state = {
    a: 1, b: 2, c: 3
  }
  bar = () => { ... }
}
```

**Comment by riceball1** [comment]
@phuchle - I can do this sounds like a good first issue for sure!

**Comment by phuchle** [comment]
Closing issue since this case is already being covered in [#73](https://github.com/5-gwoap/adopt-a-family/issues/73).
