### ISSUE TITLE
Messaging placeholder throwing console error

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/adopt-a-family#67]

**Comment by hosseinnedaee** [comment]
Hi @jwu910, could you please explain more about the issue and how reproduce it?

**Comment by jwu910** [comment]
Sorry @hosseinnedaee This project is about 2 years old, and I'm not sure where we are with this. I just checked and this error may have been fixed already. I'm going to close this issue for now.

**Comment by hosseinnedaee** [comment]
@jwu910 your welcome.
