### ISSUE TITLE
.editorconfig mixing up tabs and spaces

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/adopt-a-family#8]
config file is using tabs instead of spaces and this seems to be causing issues with our eslint `no-mixed-spaces-and-tabs` setting

**Comment by jwu910** [comment]
If anyone gets a chance to test this after this last merge, lets close this issue.

**Comment by rainrivas** [comment]
@jwu910 Setting issue to "DONE" until someone confirms it with a final test (probably when we merge everything to development)

**Comment by phuchle** [comment]
Confirmed as working and closing issue.
